#lang racket
(require racket/set racket/stream)
(require racket/fixnum)
(require "interp-Lvec.rkt")
(require "type-check-Lvec.rkt")
(require "interp-Lvec-prime.rkt")
(require "interp-Cvec.rkt")
(require "type-check-Cvec.rkt")
(require "interp.rkt")
(require "passes/shrink.rkt")
(require "passes/uniquify.rkt")
(require "passes/uncover-get.rkt")
(require "passes/expose-allocation.rkt")
(require "passes/remove-complex-opera.rkt")
(require "passes/explicate-control.rkt")
(require "passes/select-instructions.rkt")
(require "passes/uncover-live.rkt")
(require "passes/build-interference.rkt")
(require "passes/allocate-registers.rkt")
(require "passes/patch-instructions.rkt")
(require "passes/prelude-and-conclusion.rkt")
(provide (all-defined-out))


;; Define the compiler passes to be used by interp-tests and the grader
;; Note that your compiler file (the file that defines the passes)
;; must be named "compiler.rkt"
(define compiler-passes
  `(("shrink" ,shrink ,interp-Lvec #;,type-check-Lvec)
    ("uniquify" ,uniquify ,interp-Lvec #;,type-check-Lvec)
    ("expose allocation" ,expose-allocation ,interp-Lvec-prime #;,type-check-Lvec)
    ("uncover get!" ,uncover-get! ,interp-Lvec-prime #;,type-check-Lvec)
    ("remove complex opera*" ,remove-complex-opera* ,interp-Lvec-prime #;,type-check-Lvec)
    ("explicate control" ,explicate-control ,interp-Cvec #;,type-check-Cvec)
    ("select instruction" ,select-instructions ,interp-pseudo-x86-2)
    ("uncover live" ,uncover-live ,interp-pseudo-x86-2)
    ("build interference" ,build-interference ,interp-pseudo-x86-2)
    ("allocate registers" ,allocate-registers ,interp-x86-2)
    ("patch instructions" ,patch-instructions ,interp-x86-2)
    ("prelude and conclusion" ,prelude-and-conclusion ,interp-x86-2)
    )
  )

