#lang racket
(require racket/set racket/stream)
(require racket/fixnum)
(require "interp-Lfun.rkt")
(require "type-check-Lfun.rkt")
(require "interp-Lfun-prime.rkt")
(require "interp-Cfun.rkt")
(require "type-check-Cfun.rkt")
(require "interp.rkt")
(require "passes/shrink.rkt")
(require "passes/uniquify.rkt")
(require "passes/uncover-get.rkt")
(require "passes/reveal-functions.rkt")
(require "passes/limit-functions.rkt")
(require "passes/expose-allocation.rkt")
(require "passes/remove-complex-opera.rkt")
(require "passes/explicate-control.rkt")
(require "passes/select-instructions.rkt")
(require "passes/uncover-live.rkt")
(require "passes/build-interference.rkt")
(require "passes/allocate-registers.rkt")
(require "passes/patch-instructions.rkt")
(require "passes/prelude-and-conclusion.rkt")
(provide (all-defined-out))


;; Define the compiler passes to be used by interp-tests and the grader
;; Note that your compiler file (the file that defines the passes)
;; must be named "compiler.rkt"
(define compiler-passes
  `(("shrink" ,shrink ,interp-Lfun #;,type-check-Lfun)
    ("uniquify" ,uniquify ,interp-Lfun #;,type-check-Lfun)
    ("uncover get!" ,uncover-get! ,interp-Lfun #;,type-check-Lfun)
    ("reveal functions" ,reveal-functions ,interp-Lfun-prime #;,type-check-Lfun)
    ("limit functions" ,limit-functions ,interp-Lfun-prime ,type-check-Lfun)
    ("expose allocation" ,expose-allocation ,interp-Lfun-prime #;,type-check-Lfun)
    ("remove complex opera*" ,remove-complex-opera* ,interp-Lfun-prime #;,type-check-Lfun)
    ("explicate control" ,explicate-control ,interp-Cfun ,type-check-Cfun)
    ;("select instruction" ,select-instructions ,interp-pseudo-x86-2)
    ;("uncover live" ,uncover-live ,interp-pseudo-x86-2)
    ;("build interference" ,build-interference ,interp-pseudo-x86-2)
    ;("allocate registers" ,allocate-registers ,interp-x86-2)
    ;("patch instructions" ,patch-instructions ,interp-x86-2)
    ;("prelude and conclusion" ,prelude-and-conclusion ,interp-x86-2)
    )
  )

